# 开发环境配置

# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://120.79.207.195:3306/zlianweb?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    username: root
    password: Mypwd123!
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    # Redis数据库索引（默认为 0）
    database: 2
    # Redis服务器地址
    host: 120.79.207.195
    # Redis服务器连接端口
    port: 6379
    # Redis 密码
    password: 123456redis
    jedis:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
    # 连接超时时间（毫秒）
    timeout: 50000

# 日志配置
logging:
  level:
    cn.zlianpay: DEBUG
    com.baomidou.mybatisplus: DEBUG
